site_name: 'Highball documentation'
theme:
  favicon: 'assets/logo.png'
  logo: 'assets/logo.png'
  name: 'material'
  palette:
    - scheme: default
      primary: 'black'
      accent: 'light green'
      toggle:
        icon: material/brightness-7
    - scheme: slate
      primary: 'black'
      accent: 'light green'
      toggle:
        icon: material/brightness-4
markdown_extensions:
  - tables
repo_name: 'highball-fedi/highball'
repo_url: 'https://github.com/highball-fedi/highball'
